# This action triggers Ansible deploy playbook in response
# to a new release being created. It uses Ansible Tower webhooks.
name: Deploy website on release publication

'on':
  release:
    types: 
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # We usually would not provision servers through this kind of pipeline,
    # but we add this here just because.
    - name: Invoke server provision hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_SERVER_PROVISION_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SERVER_PROVISION_KEY }}

    # We wait some seconds to ensure provisioned server already has an IP
    # As above, this would have no place in a real production environment.
    - name: Wait some seconds
      run: sleep 25

    # We deploy the website
    - name: Invoke website deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.WEBHOOK_WEB_DEPLOY_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_WEB_DEPLOY_KEY }}
